language: go

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install rethinkdb

install:
  - go get github.com/mattn/goveralls
  - go get github.com/pzduniak/multicov
  - go get -t -v ./apps/... ./pkg/...

before_script:
  - rethinkdb --daemon

script:
  - RETHINKDB=rethinkdb://127.0.0.1:28015/test multicov ./pkg/...
  - goveralls -coverprofile=coverage.out -service=travis-ci
