language: go

install: 
  - go get github.com/mattn/goveralls
  - cd apps && go get -t -v ./... && cd ../pkg && go get -t -v ./... && cd ../

script:
  - cd pkg && go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
