language: go

install: 
  - go get github.com/mattn/goveralls
  - go get github.com/pzduniak/multicov
  - go get -t -v ./apps/... ./pkg/...

script:
  - multicov ./pkg/...
  - goveralls -coverprofile=coverage.out -service=travis-ci
